### PR TITLE
demo refresh: revive multi-provider demo

### LINKED ISSUE #202: demo: multi-node setup broken
Multi-node setup is broken due to missing provider attributes file, and probably more

### PR DESCRIPTION
**Pull request by boz**
* _run/multi: fix for tendermint upgrade, add persistent storage, commands.
 * _run/kube: remove contour
 * cmd/akash: fixes
 * manifest: move http code to provider/manifest/http
 * provider/manifest/http: simple status endpoint.
 * util/initgen: create node key and peer ids to satisfy tendermint
   upgrade.

fixes #202
refs #238

### CODE REVIEW

File: node/util.go [hunk 1]
```diff
@@ -57,7 +58,19 @@ func PVToJSON(obj tmtypes.PrivValidator) ([]byte, error) {
 }
 
 func PVToFile(path string, perm os.FileMode, obj tmtypes.PrivValidator) error {
-	data, err := PVToJSON(obj)
+	return writeConfigIfNotExist(path, perm, obj)
+}
+
+func NodeKeyToJSON(obj *p2p.NodeKey) ([]byte, error) {
```
Comment (golangci) [inline node/util.go]: func name will be used as node.NodeKeyToJSON by other packages, and that stutters; consider calling this KeyToJSON

File: node/util.go [hunk 2]
```diff
@@ -57,7 +58,19 @@ func PVToJSON(obj tmtypes.PrivValidator) ([]byte, error) {
...
+	return cdc.MarshalJSON(obj)
+}
+
+func NodeKeyToFile(path string, perm os.FileMode, obj *p2p.NodeKey) error {
```
Comment (golangci) [inline node/util.go]: func name will be used as node.NodeKeyToFile by other packages, and that stutters; consider calling this KeyToFile

File: provider/manifest/http/server.go [hunk 3]
```diff
@@ -82,9 +84,19 @@ func requestLogger(log log.Logger) mux.MiddlewareFunc {
 	}
 }
 
+func newStatusHandler(log log.Logger,
+	phandler manifest.Handler) func(http.ResponseWriter, *http.Request) {
+	return func(w http.ResponseWriter, r *http.Request) {
+		w.Header().Set("Content-Type", "text/plain; charset=us-ascii")
+		w.Write([]byte("OK\n"))
```
Comment (golangci) [inline provider/manifest/http/server.go]: Error return value of `w.Write` is not checked

File: util/initgen/helm.go [hunk 4]
```diff
@@ -75,10 +91,21 @@ func (w helmWriter) Write() error {
 	return ioutil.WriteFile(opath, buf, 0644)
 }
 
+func (w helmWriter) nodeP2PHost(node *Node) string {
```
Comment (golangci) [inline util/initgen/helm.go]: func helmWriter.nodeP2PHost is unused
