### PR TITLE
Fix tests on master

### LINKED ISSUE #466: Fix tests on master
### Akash version

branch `master`: commit `9161a1a`

### What happened

Tests failing:

```
package github.com/ovrclk/akash/cmd/common (test)
	imports github.com/ovrclk/akash/marketplace: no matching versions for query "latest"
FAIL	github.com/ovrclk/akash/cmd/common [setup failed]
# github.com/ovrclk/akash/manifest
import cycle not allowed in test
package github.com/ovrclk/akash/manifest (test)
	imports github.com/ovrclk/akash/sdl
	imports github.com/ovrclk/akash/manifest
FAIL	github.com/ovrclk/akash/manifest [setup failed]
# github.com/ovrclk/akash/pkg/apis/akash.network/v1
package github.com/ovrclk/akash/manifest (test)
	imports github.com/ovrclk/akash/testutil: no matching versions for query "latest"
FAIL	github.com/ovrclk/akash/pkg/apis/akash.network/v1 [setup failed]
# github.com/ovrclk/akash/provider/bidengine
package github.com/ovrclk/akash/provider/bidengine_test
	imports github.com/ovrclk/akash/provider/cluster/mocks: no matching versions for query "latest"
FAIL	github.com/ovrclk/akash/provider/bidengine [setup failed]
# github.com/ovrclk/akash/provider/cluster
package github.com/ovrclk/akash/provider/bidengine_test
	imports github.com/ovrclk/akash/provider/cluster/mocks: no matching versions for query "latest"
FAIL	github.com/ovrclk/akash/provider/cluster [setup failed]
# github.com/ovrclk/akash/provider/cluster/kube
package github.com/ovrclk/akash/manifest (test)
	imports github.com/ovrclk/akash/testutil: no matching versions for query "latest"
FAIL	github.com/ovrclk/akash/provider/cluster/kube [setup failed]
# github.com/ovrclk/akash/provider/manifest
package github.com/ovrclk/akash/provider/bidengine_test
	imports github.com/ovrclk/akash/query/mocks: no matching versions for query "latest"
FAIL	github.com/ovrclk/akash/provider/manifest [setup failed]
# github.com/ovrclk/akash/pubsub
package github.com/ovrclk/akash/manifest (test)
	imports github.com/ovrclk/akash/testutil: no matching versions for query "latest"
FAIL	github.com/ovrclk/akash/pubsub [setup failed]
# github.com/ovrclk/akash/x/provider/handler
x/provider/handler/handler.go:54:39: Wrapf call has arguments but no formatting directives
# github.com/ovrclk/akash/sdl_test [github.com/ovrclk/akash/sdl.test]
sdl/v1_test.go:32:21: group.GetRequirements undefined (type *"github.com/ovrclk/akash/x/deployment/types".GroupSpec has no field or method GetRequirements)
sdl/v1_test.go:34:18: undefined: "github.com/ovrclk/akash/types".ProviderAttribute
sdl/v1_test.go:37:10: group.GetRequirements undefined (type *"github.com/ovrclk/akash/x/deployment/types".GroupSpec has no field or method GetRequirements)
sdl/v1_test.go:41:37: invalid composite literal type "github.com/ovrclk/akash/types".ResourceGroup
sdl/v1_test.go:56:19: undefined: "github.com/ovrclk/akash/types".ManifestGroup
sdl/v1_test.go:87:20: mani.Groups undefined (type manifest.Manifest has no field or method Groups)
# github.com/ovrclk/akash/validation_test [github.com/ovrclk/akash/validation.test]
validation/manifest_test.go:16:14: undefined: "github.com/ovrclk/akash/types".ManifestGroup
validation/manifest_test.go:17:14: undefined: "github.com/ovrclk/akash/types".DeploymentGroup
validation/manifest_test.go:27:16: undefined: "github.com/ovrclk/akash/types".ManifestGroup
validation/manifest_test.go:43:16: undefined: "github.com/ovrclk/akash/types".DeploymentGroup
validation/manifest_test.go:63:16: undefined: "github.com/ovrclk/akash/types".ManifestGroup
validation/manifest_test.go:88:16: undefined: "github.com/ovrclk/akash/types".DeploymentGroup
validation/manifest_test.go:108:16: undefined: "github.com/ovrclk/akash/types".ManifestGroup
validation/manifest_test.go:124:16: undefined: "github.com/ovrclk/akash/types".DeploymentGroup
validation/manifest_test.go:152:16: undefined: "github.com/ovrclk/akash/types".ManifestGroup
validation/manifest_test.go:168:16: undefined: "github.com/ovrclk/akash/types".DeploymentGroup
validation/manifest_test.go:168:16: too many errors
```

### What did you expect to happen

Tests should pass on the default branch

### How to reproduce it

`make test`

### PR DESCRIPTION
**Pull request by akhilkumarpilli**
Fixes #466

### CODE REVIEW

File: provider/cluster/kube/client_test.go [hunk 1]
```diff
@@ -16,11 +16,6 @@ func kubeClient(t *testing.T) Client {
...
 }
 
-func leaseID(t *testing.T) types.LeaseID {
-	return types.LeaseID{
-		Deployment: []byte(t.Name()),
-		Group:      0,
-		Order:      0,
-		Provider:   []byte(t.Name()),
-	}
+func leaseID(t *testing.T) mtypes.LeaseID {
```
Comment (golangcibot) [inline provider/cluster/kube/client_test.go:19]: func `leaseID` is unused (from `unused`)

File: pubsub/bus_test.go [hunk 2]
```diff
@@ -147,3 +153,20 @@ type testEvent []byte
...
+
+func SleepForThreadStart(t *testing.T) {
+	time.Sleep(delayThreadStart(t))
+}
+
+func delayThreadStart(t *testing.T) time.Duration {
+	if val := os.Getenv("TEST_DELAY_THREAD_START"); val != "" {
+		d, err := time.ParseDuration(val)
+		require.NoError(t, err)
+		return d
```
Comment (golangcibot) [inline pubsub/bus_test.go:169]: return statements should not be cuddled if block has more than two lines (from `wsl`)

File: pubsub/bus_test.go [hunk 3]
```diff
@@ -147,3 +153,20 @@ type testEvent []byte
...
+	}
+	return defaultDelayThreadStart
```
Comment (golangcibot) [inline pubsub/bus_test.go:171]: return statements should not be cuddled if block has more than two lines (from `wsl`)

File: provider/cluster/kube/deployment_test.go [hunk 4]
```diff
@@ -4,16 +4,26 @@ import (
...
 	"github.com/stretchr/testify/assert"
 	"github.com/stretchr/testify/require"
+	"github.com/tendermint/tendermint/crypto/ed25519"
 	"github.com/tendermint/tendermint/libs/log"
 )
 
 func TestDeploy(t *testing.T) {
 	t.Skip()
-	lease := testutil.Lease(testutil.Address(t), testutil.Address(t), 1, 2, 3)
+	owner := ed25519.GenPrivKey().PubKey().Address()
```
Comment (golangcibot) [inline provider/cluster/kube/deployment_test.go:18]: assignments should only be cuddled with other assignments (from `wsl`)

File: pkg/apis/akash.network/v1/types_test.go [hunk 5]
```diff
@@ -3,38 +3,56 @@ package v1
...
+	"github.com/tendermint/tendermint/crypto/ed25519"
 )
 
 func TestToProto(t *testing.T) {
-	lease := testutil.Lease(testutil.Address(t), testutil.Address(t), 1, 2, 3)
+	owner := ed25519.GenPrivKey().PubKey().Address()
+	provider := ed25519.GenPrivKey().PubKey().Address()
+	leaseID := mtypes.LeaseID{
+		Owner:    sdk.AccAddress(owner),
+		DSeq:     1,
```
Comment (golangcibot) [inline pkg/apis/akash.network/v1/types_test.go:19]: mnd: Magic number: 1, in <assign> detected (from `gomnd`)

File: pkg/apis/akash.network/v1/types_test.go [hunk 6]
```diff
@@ -3,38 +3,56 @@ package v1
...
+		GSeq:     1,
```
Comment (golangcibot) [inline pkg/apis/akash.network/v1/types_test.go:20]: mnd: Magic number: 1, in <assign> detected (from `gomnd`)

File: pkg/apis/akash.network/v1/types_test.go [hunk 7]
```diff
@@ -3,38 +3,56 @@ package v1
...
+		OSeq:     1,
```
Comment (golangcibot) [inline pkg/apis/akash.network/v1/types_test.go:21]: mnd: Magic number: 1, in <assign> detected (from `gomnd`)

File: provider/cluster/inventory_test.go [hunk 8]
```diff
@@ -5,31 +5,32 @@ import (
...
 			allocated: allocated,
-			resources: &types.DeploymentGroup{Resources: res},
+			resources: &dtypes.GroupSpec{Resources: res},
 		}
 	}
 
 	inventory := []Node{
-		NewNode("a", types.ResourceUnit{CPU: 1000, Memory: 10 * unit.Gi}),
-		NewNode("b", types.ResourceUnit{CPU: 1000, Memory: 10 * unit.Gi}),
+		NewNode("a", types.Unit{CPU: 1000, Memory: 10 * unit.Gi}),
```
Comment (golangcibot) [inline provider/cluster/inventory_test.go:32]: mnd: Magic number: 1000, in <assign> detected (from `gomnd`)

File: provider/cluster/inventory_test.go [hunk 9]
```diff
@@ -5,31 +5,32 @@ import (
...
+		NewNode("b", types.Unit{CPU: 1000, Memory: 10 * unit.Gi}),
```
Comment (golangcibot) [inline provider/cluster/inventory_test.go:33]: mnd: Magic number: 1000, in <assign> detected (from `gomnd`)

File: sdl/v1_test.go [hunk 10]
```diff
@@ -21,30 +21,29 @@ func Test_v1_Parse_docs(t *testing.T) {
...
-	assert.Equal(t, types.ResourceGroup{
+	assert.Equal(t, types.Resource{
 		Count: 2,
-		Price: 0x1388,
-		Unit: types.ResourceUnit{
-			CPU:    100,
-			Memory: 128 * unit.Mi,
-			Disk:   1 * unit.Gi,
+		Unit: types.Unit{
+			CPU:     100,
```
Comment (golangcibot) [inline sdl/v1_test.go:44]: mnd: Magic number: 100, in <assign> detected (from `gomnd`)

File: sdl/v1_test.go [hunk 11]
```diff
@@ -21,30 +21,29 @@ func Test_v1_Parse_docs(t *testing.T) {
...
+			Memory:  128 * unit.Mi,
```
Comment (golangcibot) [inline sdl/v1_test.go:45]: mnd: Magic number: 128, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 12]
```diff
@@ -24,33 +26,35 @@ func Test_ValidateManifest(t *testing.T) {
...
-					Services: []*types.ManifestService{
+					Services: []manifest.Service{
 						{
 							Name: "svc1",
-							Unit: &types.ResourceUnit{
-								CPU:    10,
-								Memory: 20,
-								Disk:   5,
+							Unit: types.Unit{
+								CPU:     10,
```
Comment (golangcibot) [inline validation/manifest_test.go:36]: mnd: Magic number: 10, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 13]
```diff
@@ -24,33 +26,35 @@ func Test_ValidateManifest(t *testing.T) {
...
+								Memory:  20,
```
Comment (golangcibot) [inline validation/manifest_test.go:37]: mnd: Magic number: 20, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 14]
```diff
@@ -24,33 +26,35 @@ func Test_ValidateManifest(t *testing.T) {
...
+								Storage: 5,
```
Comment (golangcibot) [inline validation/manifest_test.go:38]: mnd: Magic number: 5, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 15]
```diff
@@ -24,33 +26,35 @@ func Test_ValidateManifest(t *testing.T) {
...
-							Unit: types.ResourceUnit{
-								CPU:    10,
-								Memory: 20,
-								Disk:   5,
+					GroupSpec: dtypes.GroupSpec{
+						Name: "foo",
+						Resources: []dtypes.Resource{
+							{
+								Unit: types.Unit{
+									CPU:     10,
```
Comment (golangcibot) [inline validation/manifest_test.go:52]: mnd: Magic number: 10, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 16]
```diff
@@ -24,33 +26,35 @@ func Test_ValidateManifest(t *testing.T) {
...
+									Memory:  20,
```
Comment (golangcibot) [inline validation/manifest_test.go:53]: mnd: Magic number: 20, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 17]
```diff
@@ -24,33 +26,35 @@ func Test_ValidateManifest(t *testing.T) {
...
+									Storage: 5,
```
Comment (golangcibot) [inline validation/manifest_test.go:54]: mnd: Magic number: 5, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 18]
```diff
@@ -24,33 +26,35 @@ func Test_ValidateManifest(t *testing.T) {
...
+								},
+								Count: 3,
```
Comment (golangcibot) [inline validation/manifest_test.go:56]: mnd: Magic number: 3, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 19]
```diff
@@ -60,42 +64,44 @@ func Test_ValidateManifest(t *testing.T) {
...
-					Services: []*types.ManifestService{
+					Services: []manifest.Service{
 						{
 							Name: "svc1",
-							Unit: &types.ResourceUnit{
-								CPU:    10,
-								Memory: 20,
-								Disk:   5,
+							Unit: types.Unit{
+								CPU:     10,
```
Comment (golangcibot) [inline validation/manifest_test.go:74]: mnd: Magic number: 10, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 20]
```diff
@@ -60,42 +64,44 @@ func Test_ValidateManifest(t *testing.T) {
...
+								Memory:  20,
```
Comment (golangcibot) [inline validation/manifest_test.go:75]: mnd: Magic number: 20, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 21]
```diff
@@ -60,42 +64,44 @@ func Test_ValidateManifest(t *testing.T) {
...
+								Storage: 5,
```
Comment (golangcibot) [inline validation/manifest_test.go:76]: mnd: Magic number: 5, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 22]
```diff
@@ -60,42 +64,44 @@ func Test_ValidateManifest(t *testing.T) {
...
+					GroupSpec: dtypes.GroupSpec{
+						Name: "foo",
+						Resources: []dtypes.Resource{
+							{
+								Unit: types.Unit{
+									CPU:     10,
+									Memory:  20,
+									Storage: 5,
+								},
+								Count: 3,
```
Comment (golangcibot) [inline validation/manifest_test.go:103]: mnd: Magic number: 3, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 23]
```diff
@@ -105,41 +111,43 @@ func Test_ValidateManifest(t *testing.T) {
...
+					GroupSpec: dtypes.GroupSpec{
+						Name: "foo",
+						Resources: []dtypes.Resource{
+							{
+								Unit: types.Unit{
+									CPU:     10,
+									Memory:  20,
+									Storage: 5,
+								},
+								Count: 2,
```
Comment (golangcibot) [inline validation/manifest_test.go:141]: mnd: Magic number: 2, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 24]
```diff
@@ -149,33 +157,35 @@ func Test_ValidateManifest(t *testing.T) {
...
+					GroupSpec: dtypes.GroupSpec{
+						Name: "foo",
+						Resources: []dtypes.Resource{
+							{
+								Unit: types.Unit{
+									CPU:     10,
+									Memory:  20,
+									Storage: 5,
+								},
+								Count: 3,
```
Comment (golangcibot) [inline validation/manifest_test.go:187]: mnd: Magic number: 3, in <assign> detected (from `gomnd`)

File: pkg/apis/akash.network/v1/types_test.go [hunk 25]
```diff
@@ -3,38 +3,58 @@ package v1
...
 )
 
 func TestToProto(t *testing.T) {
-	lease := testutil.Lease(testutil.Address(t), testutil.Address(t), 1, 2, 3)
+	owner := ed25519.GenPrivKey().PubKey().Address()
+	provider := ed25519.GenPrivKey().PubKey().Address()
+
+	leaseID := mtypes.LeaseID{
+		Owner:    sdk.AccAddress(owner),
+		DSeq:     uint64(1),
```
Comment (golangcibot) [inline pkg/apis/akash.network/v1/types_test.go:20]: mnd: Magic number: 1, in <argument> detected (from `gomnd`)

File: pkg/apis/akash.network/v1/types_test.go [hunk 26]
```diff
@@ -3,38 +3,58 @@ package v1
...
+		GSeq:     uint32(2),
```
Comment (golangcibot) [inline pkg/apis/akash.network/v1/types_test.go:21]: mnd: Magic number: 2, in <argument> detected (from `gomnd`)

File: pkg/apis/akash.network/v1/types_test.go [hunk 27]
```diff
@@ -3,38 +3,58 @@ package v1
...
+		OSeq:     uint32(3),
```
Comment (golangcibot) [inline pkg/apis/akash.network/v1/types_test.go:22]: mnd: Magic number: 3, in <argument> detected (from `gomnd`)

File: pkg/apis/akash.network/v1/types_test.go [hunk 28]
```diff
@@ -3,38 +3,58 @@ package v1
...
 }
 
 func TestFromProto(t *testing.T) {
-	lease := testutil.Lease(testutil.Address(t), testutil.Address(t), 1, 2, 3)
+	owner := ed25519.GenPrivKey().PubKey().Address()
+	provider := ed25519.GenPrivKey().PubKey().Address()
+
+	leaseID := mtypes.LeaseID{
+		Owner:    sdk.AccAddress(owner),
+		DSeq:     uint64(1),
```
Comment (golangcibot) [inline pkg/apis/akash.network/v1/types_test.go:42]: mnd: Magic number: 1, in <argument> detected (from `gomnd`)

File: pkg/apis/akash.network/v1/types_test.go [hunk 29]
```diff
@@ -3,38 +3,58 @@ package v1
...
+		GSeq:     uint32(2),
```
Comment (golangcibot) [inline pkg/apis/akash.network/v1/types_test.go:43]: mnd: Magic number: 2, in <argument> detected (from `gomnd`)

File: pkg/apis/akash.network/v1/types_test.go [hunk 30]
```diff
@@ -3,38 +3,58 @@ package v1
...
+		OSeq:     uint32(3),
```
Comment (golangcibot) [inline pkg/apis/akash.network/v1/types_test.go:44]: mnd: Magic number: 3, in <argument> detected (from `gomnd`)

File: provider/cluster/kube/deployment_test.go [hunk 31]
```diff
@@ -4,16 +4,28 @@ import (
...
 func TestDeploy(t *testing.T) {
 	t.Skip()
-	lease := testutil.Lease(testutil.Address(t), testutil.Address(t), 1, 2, 3)
+
+	owner := ed25519.GenPrivKey().PubKey().Address()
+	provider := ed25519.GenPrivKey().PubKey().Address()
+
+	leaseID := mtypes.LeaseID{
+		Owner:    sdk.AccAddress(owner),
+		DSeq:     uint64(1),
```
Comment (golangcibot) [inline provider/cluster/kube/deployment_test.go:24]: mnd: Magic number: 1, in <argument> detected (from `gomnd`)

File: provider/cluster/kube/deployment_test.go [hunk 32]
```diff
@@ -4,16 +4,28 @@ import (
...
+		GSeq:     uint32(2),
```
Comment (golangcibot) [inline provider/cluster/kube/deployment_test.go:25]: mnd: Magic number: 2, in <argument> detected (from `gomnd`)

File: provider/cluster/kube/deployment_test.go [hunk 33]
```diff
@@ -4,16 +4,28 @@ import (
...
+		OSeq:     uint32(3),
```
Comment (golangcibot) [inline provider/cluster/kube/deployment_test.go:26]: mnd: Magic number: 3, in <argument> detected (from `gomnd`)

File: sdl/v1_test.go [hunk 34]
```diff
@@ -21,30 +21,29 @@ func Test_v1_Parse_docs(t *testing.T) {
...
+			Storage: 1 * unit.Gi,
```
Comment (golangcibot) [inline sdl/v1_test.go:46]: mnd: Magic number: 1, in <assign> detected (from `gomnd`)

File: validation/manifest_test.go [hunk 35]
```diff
@@ -105,41 +111,43 @@ func Test_ValidateManifest(t *testing.T) {
...
-								CPU:    10,
-								Memory: 20,
-								Disk:   5,
+							{
+								Unit: types.Unit{
+									CPU:     10,
+									Memory:  20,
+									Storage: 5,
+								},
+								Count: 1,
```
Comment (golangcibot) [inline validation/manifest_test.go:149]: mnd: Magic number: 1, in <assign> detected (from `gomnd`)

File: pubsub/bus_test.go [hunk 36]
```diff
@@ -94,33 +100,33 @@ func TestClone(t *testing.T) {
 	select {
 	case <-sub1.Events():
 		require.Fail(t, "spurious event")
-	case <-testutil.AfterThreadStart(t):
```
Comment (anilCSE) [inline pubsub/bus_test.go:97]: @akhilkumarpilli can we use testutil for all these functions?

File: validation/manifest_test.go [hunk 37]
```diff
@@ -221,35 +233,35 @@ func Test_ValidateManifest(t *testing.T) {
...
-
-		if test.ok {
-			assert.NoError(t, err, test.name)
-		} else {
-			assert.Error(t, err, test.name)
-		}
+		m := manifest.Manifest(test.mgroups)
+		err := validation.ValidateManifestWithDeployment(&m, test.dgroups)
+		assert.NoError(t, err, test.name)
+		// if test.ok {
```
Comment (anilCSE) [inline validation/manifest_test.go:260]: I think this should be there

File: validation/manifest_test.go [hunk 38]
```diff
@@ -221,35 +233,35 @@ func Test_ValidateManifest(t *testing.T) {
...
-		err := validation.ValidateManifestWithDeployment(m, test.dgroups)
-
-		if test.ok {
-			assert.NoError(t, err, test.name)
-		} else {
-			assert.Error(t, err, test.name)
-		}
+		m := manifest.Manifest(test.mgroups)
+		err := validation.ValidateManifestWithDeployment(&m, test.dgroups)
+		assert.NoError(t, err, test.name)
```
Comment (anilCSE) [inline validation/manifest_test.go:259]: Lets have errors cases too in the tests 
```suggestion
		if test.ok {
			assert.NoError(t, err, test.name)
		} else {
			assert.Error(t, err, test.name)
		}
```

File: cmd/common/monitor_test.go [hunk 39]
```diff
@@ -1,50 +0,0 @@
-package common
```
Comment (anilCSE) [inline cmd/common/monitor_test.go:1]: Don't we require this anymore?

File: manifest/manifest_test.go [hunk 40]
```diff
@@ -1,170 +1,159 @@
...
-			{
-				Name: "otherManifest",
-			},
-		},
-	})
-	require.NoError(t, err)
-
-	assert.NotEqual(t, hash, otherHash)
-}
+// func TestSignManifest(t *testing.T) {
```
Comment (anilCSE) [inline manifest/manifest_test.go:3]: Is there a chance to use these in future?

File: cmd/common/monitor_test.go (hunk 39 above)
Comment (akhilkumarpilli) [reply cmd/common/monitor_test.go:1]: Monitor file is already removed. So I don't think, this is required anymore.

File: manifest/manifest_test.go (hunk 40 above)
Comment (akhilkumarpilli) [reply manifest/manifest_test.go:3]: Code related to these tests is commented, so I just kept them commented

File: manifest/manifest_test.go [hunk 41]
```diff
@@ -1,170 +1,159 @@
...
+// 	sdl, err := sdl.ReadFile("../_docs/deployment.yml")
+// 	require.NoError(t, err)
+
+// 	mani, err := sdl.Manifest()
+// 	require.NoError(t, err)
+
+// 	_, kmgr := testutil.NewNamedKey(t)
```
Comment (boz) [inline manifest/manifest_test.go:10]: just delete the file.
