### PR TITLE
fix(cli): make owner flag optional

### LINKED ISSUE #1274: set the default owner as the address from the key specified with --from flag
The akash address used in the `--owner` flag can be derived from the key specified with the `--from` flag.

### PR DESCRIPTION
**Pull request by rsum1**
fixes #1274

### CODE REVIEW

File: x/market/client/cli/tx.go [hunk 1]
```diff
@@ -155,7 +156,7 @@ func cmdLeaseCreate(key string) *cobra.Command {
 				return err
 			}
 
-			id, err := BidIDFromFlagsWithoutCtx(cmd.Flags())
```
Comment (boz) [inline x/market/client/cli/tx.go:158]: I think we can get rid of these `*With(out)?Ctx` functions :confetti_ball:

**Review by boz — COMMENTED** [review]
Looks great.  I think that there's some cleanup we can do (comment inline)

File: x/market/client/cli/tx.go (hunk 1 above)
Comment (troian) [reply x/market/client/cli/tx.go:158]: 💯

**Review by hydrogen18 — APPROVED** [review]
