### PR TITLE
fix: adjust MaxGroupMemPrice

### LINKED ISSUE #640: provider bid pricing: adjust bid price config
The [current](https://github.com/ovrclk/akash/blob/21f9cb626a4cc2b490d9f9d245ed5742dd33ba57/provider/bidengine/pricing.go#L12) bid price calculation was formulated for our first testnet in 2018.  It chooses a random value between a min and max price that is determined by a configurable price per gigabyte range.

For some reason, [`calculatePrice()`](https://github.com/ovrclk/akash/blob/21f9cb626a4cc2b490d9f9d245ed5742dd33ba57/provider/bidengine/pricing.go#L12) is returning a very small range (`[0,1]`).  This might be config or it might be that the deployment price is set too low (we should use higher prices in our examples).

### PR DESCRIPTION
**Pull request by troian**
if total amount of memory in group less then 1G
calculatePriceRange will always return range 0..1.

fixes #640 ?

### CODE REVIEW

File: validation/config.go [hunk 1]
```diff
@@ -35,6 +39,10 @@ func init() {
 	if err := env.Parse(&defaultConfig); err != nil {
 		panic(err)
 	}
+
+	if defaultConfig.MaxGroupMemPrice < minDefaultMaxGroupMemPrice {
+		panic("invalid max group memory price")
+	}
```
Comment (boz) [inline validation/config.go:45]: let's not do this.  i agree with the sentiment but we should handle it more gracefully.  probably need to refactor the way this validation works - it was added in a rush to make a (2018) testnet more user-friendly.

just skip it for now

Comment (troian) [reply validation/config.go:45]: `fmt.Println` instead of panic?

Comment (boz) [reply validation/config.go:45]: nah.

Comment (boz) [reply validation/config.go:45]: everything still works fine with a lower value, right?  it's just that the prices are lower than we'd like.

Comment (troian) [reply validation/config.go:45]: kk. makes sense
