### PR TITLE
Fix golint warnings

### LINKED ISSUE #549: lint: fix golint
* Fix `golint` warnings from the [lint checker](https://github.com/ovrclk/akash/blob/master/.github/workflows/tests.yml#L39) step for it.
 * Remove `continue-on-error: true` from `lint golint` step.

### PR DESCRIPTION
**Pull request by akhilkumarpilli**
Fixes #549

### CODE REVIEW

File: provider/cluster/kube/config.go [hunk 1]
```diff
@@ -5,7 +5,8 @@ import (
 	corev1 "k8s.io/api/core/v1"
 )
 
-type config_ struct {
+// Config is the struct that stores kube config
+type Config struct {
```
Comment (boz) [inline provider/cluster/kube/config.go:9]: keep this private to the package

Comment (akhilkumarpilli) [reply provider/cluster/kube/config.go]: Yeah, changed it to private but renamed it to `kubeconfig` just to avoid warning `don't use underscores in go names`

**Comment by akhilkumarpilli** [comment]
Sure @boz, Can I know what are generated dirs so that I can ignore them.

**Comment by boz** [comment]
It's everything below `pkg/client`.  Maybe let's wait until [this](https://github.com/ovrclk/akash/pull/589/files#diff-f5e6ed72f74bd5711969dc7bbe35ac73R9) PR is merged so that the directories will be ignored by the linter automatically.

**Comment by akhilkumarpilli** [comment]
@boz, I tried by ignoring generated dirs in `.golangci.yml` using `skip-dirs`. But still `golint` is reporting issues from generated dirs.

**Comment by akhilkumarpilli** [comment]
@boz, ignored generated dirs and fixed everything.
