### PR TITLE
fix(provider): query provider if flag is not supplied for send-manifest

### LINKED ISSUE #1177: send-manifest requires --provider
You should be able to only pass `--dseq`.

### PR DESCRIPTION
**Pull request by troian**
fixes #1177

output examples
**text**
```text
provider: akash1f6gmtjpx4r8qda9nxjwq26fp5mcjyqmaq5m6j7
    status: PASS
provider: akash10cl5rm0cqnpj45knzakpa4cnvn5amzwp4lhcal
    status: PASS
```

**yaml**
```yaml
- provider: akash1f6gmtjpx4r8qda9nxjwq26fp5mcjyqmaq5m6j7
  status: PASS
- provider: akash10cl5rm0cqnpj45knzakpa4cnvn5amzwp4lhcal
  status: PASS
```

**json**
```json
[{
	"provider": "akash1f6gmtjpx4r8qda9nxjwq26fp5mcjyqmaq5m6j7",
	"status": "PASS"
}, {
	"provider": "akash10cl5rm0cqnpj45knzakpa4cnvn5amzwp4lhcal",
	"status": "PASS"
}]
```

### CODE REVIEW

File: provider/cmd/helpers.go [hunk 1]
```diff
@@ -58,3 +71,49 @@ func providerFromFlags(flags *pflag.FlagSet) (sdk.Address, error) {
 
 	return addr, nil
 }
+
+func providersFromFlagsOrQuery(flags *pflag.FlagSet, ctx context.Context, cctx client.Context, did dtypes.DeploymentID) ([]sdk.Address, error) {
+	var providers []string
+
+	if !flags.Changed(FlagProvider) {
+		cclient := akashclient.NewQueryClientFromCtx(cctx)
+		resp, err := cclient.Leases(ctx, &mtypes.QueryLeasesRequest{
```
Comment (boz) [inline provider/cmd/helpers.go:80]: It should filter leases by whatever you pass.  An owner and dseq is required, but oseq, gseq, provider can be used to specify it further.

It shouldn't accept a random provider like is done below.

**Review by boz — CHANGES_REQUESTED** [review]

File: provider/cmd/helpers.go [hunk 2]
```diff
@@ -58,3 +71,49 @@ func providerFromFlags(flags *pflag.FlagSet) (sdk.Address, error) {
...
+				DSeq:  did.DSeq,
+				State: mtypes.Lease_State_name[int32(mtypes.LeaseActive)],
+			},
+		})
+		if err != nil {
+			return nil, err
+		}
+
+		for _, lease := range resp.Leases {
+			providers = append(providers, lease.Lease.LeaseID.Provider)
```
Comment (hydrogen18) [inline provider/cmd/helpers.go:92]: Could we wind up with the same provider address multiple times here?

File: provider/cmd/manifest.go [hunk 3]
```diff
@@ -57,15 +66,75 @@ func doSendManifest(cmd *cobra.Command, sdlpath string) error {
...
+		return err
+	}
+
+	type result struct {
+		Provider sdk.Address `json:"provider" yaml:"provider"`
+		Status   string      `json:"status" yaml:"status"`
+		Error    error       `json:"error,omitempty" yaml:"error,omitempty"`
+	}
+
+	results := make([]result, 0, len(providers))
```
Comment (hydrogen18) [inline provider/cmd/manifest.go:84]: can this just do `make([]result, len(providers))` and use `results[i]` in the loop rather than `append` ?

File: provider/cmd/manifest.go [hunk 4]
```diff
@@ -57,15 +66,75 @@ func doSendManifest(cmd *cobra.Command, sdlpath string) error {
...
-	gclient, err := gwrest.NewClient(akashclient.NewQueryClientFromCtx(cctx), prov, []tls.Certificate{cert})
+	_, err = fmt.Fprint(cmd.OutOrStdout(), buf.String())
+
 	if err != nil {
 		return err
 	}
 
-	return showErrorToUser(gclient.SubmitManifest(context.Background(), dseq, mani))
+	if submitFailed {
+		return errors.Errorf("submit manifest to some providers has been failed")
```
Comment (hydrogen18) [inline provider/cmd/manifest.go:136]: This can be assigned statically I think like `var errSubmitManifestFailed = errors.New(...)`

File: provider/cmd/manifest.go (hunk 3 above)
Comment (boz) [reply provider/cmd/manifest.go:84]: I tend to go with the three-argument version to make the loops independent of how it's allocated or if you're actually appending, etc...

File: provider/cmd/helpers.go (hunk 2 above)
Comment (troian) [reply provider/cmd/helpers.go:92]: there shouldn't be multiple leases for one dseq on provider

**Review by hydrogen18 — APPROVED** [review]

**Review by boz — APPROVED** [review]
:rocket:
