### PR TITLE
fix: reject updates on provider attributes

### LINKED ISSUE #643: design: should provider attribute updates affect current leases?
Currently, if a provider changes their attributes such that they are incompatible with leases that the provider has open, the existing leases are not affected.

We have three options:

1. Status quo
1. Should existing, incompatible leases be closed?
1. Should we disallow incompatible updates?

I prefer the third option because it forces providers to understand what they are doing while at the same time keeping committed state consistent with an invariant that the provider's attributes are compatible with an order's group attributes for all open leases.

### PR DESCRIPTION
**Pull request by troian**
fixes #643

### CODE REVIEW

**Comment by boz** [comment]
@troian I'm sorry this wasn't clear - we want to prohibit attribute changes that are incompatible with active leases that the provider has.

So if a provider p1 has attributes

```
region: us-west
class: b
```

and two leases for groups that have required attributes:

```
- id: 1
  attributes:
    region: us-west
    class: b
- id: 2
  attributes:
    region: us-west
```

the provider would not be able to remove its attribute `class: b` until lease 1 is closed.

does that make sense?

**Comment by troian** [comment]
Gotcha

File: x/provider/handler/handler.go [hunk 1]
```diff
@@ -44,16 +46,35 @@ func handleMsgCreate(ctx sdk.Context, keeper keeper.Keeper, msg types.MsgCreateP
...
+	prov, found := keeper.Get(ctx, msg.Owner)
+	if !found {
 		return nil, errors.Wrapf(types.ErrProviderNotFound, "id: %s", msg.Owner)
 	}
 
+	attributeChangesPermitted := true
+
+	// all filtering code below is madness!. should make an index to not melt the cpu
+	mkeeper.WithLeases(ctx, func(lease mtypes.Lease) bool {
+		if prov.Owner.Equals(lease.Provider) && lease.State != mtypes.LeaseClosed {
```
Comment (boz) [inline x/provider/handler/handler.go:59]: I believe that `InsufficientFunds` is a terminal state too.  I think this would be safer:

```go
if !(prov.Owner.Equals(lease.Provider) && lease.State == mtypes.Leaseactive) {
  return false
}
```

File: x/provider/handler/handler.go [hunk 2]
```diff
@@ -44,16 +46,35 @@ func handleMsgCreate(ctx sdk.Context, keeper keeper.Keeper, msg types.MsgCreateP
...
+			// shall we manifest a bit of wonder in case order is not found?
```
Comment (boz) [inline x/provider/handler/handler.go:60]: maybe, just to be safe, I guess.

File: x/provider/types/errors.go [hunk 3]
```diff
@@ -31,4 +32,7 @@ var (
 
 	// ErrAttributes error code for provider attribute problems
 	ErrAttributes = sdkerrors.Register(ModuleName, errAttributes, "attribute specification error")
+
+	// ErrAttributesImmutable error code for attributes update
+	ErrAttributesImmutable = sdkerrors.Register(ModuleName, errAttributesImmutable, "attributes cannot be changed")
```
Comment (boz) [inline x/provider/types/errors.go:37]: `ErrIncompatibleAttributes` or something?

File: x/provider/handler/handler.go (hunk 1 above)
Comment (boz) [reply x/provider/handler/handler.go:59]: maybe create and use `mkeeper.LeasesForProvider()` so we can better keep track of where indexes are needed and to abstract away the use of those indexes.

Comment (troian) [reply x/provider/handler/handler.go:59]: Maybe better to keep it as is. actual filtering is provider specific only. It introduces double iteration through leases.

Comment (troian) [reply x/provider/handler/handler.go:59]: won't work
```go
if !(prov.Owner.Equals(lease.Provider) && lease.State == mtypes.Leaseactive) {
  return false
}
```

this should do
```go
if prov.Owner.Equals(lease.Provider) && (lease.State == mtypes.LeaseActive) {
  return false
}
```

Comment (boz) [reply x/provider/handler/handler.go]: it's just generally nicer to exit early from things and continue on with what you want to process.

```go
// if not interested in this lease, continue on to the next
if !(prov.Owner.Equals(lease.Provider) && lease.State == mtypes.Leaseactive) {
  return false
}
order, found := mkeeper.GetOrder(...)
// ...
return true
```

but all good, just a preference.  it works great as is.

Comment (troian) [reply x/provider/handler/handler.go]: Yah, my bad, should reorder
