### PR TITLE
fix: expand error message when manifest send fails

### LINKED ISSUE #1405: manifest api: non-descriptive error returned
`akash` just shows "error 500" instead of "version mismatch" when submitting a manifest with the wrong version [^1]

The provider logs:
```
Oct 07 22:25:32 k8s-master.provider-2.prod.ewr1 akash[457169]: I[2021-10-07|22:25:32.754] data received                                module=manifest-manager deployment=akash1apchhdvxn7u7tpnfv7c6pnhcdc7kjhcw5sz0zm/5 version=380a1693be72943aae5d46b411f70a25e2a6d9f018b32f4a9af53cf773dd102d
Oct 07 22:25:32 k8s-master.provider-2.prod.ewr1 akash[457169]: I[2021-10-07|22:25:32.755] deployment version mismatch                  module=manifest-manager deployment=akash1apchhdvxn7u7tpnfv7c6pnhcdc7kjhcw5sz0zm/5 expected=380A1693BE72943AAE5D46B411F70A25E2A6D9F018B32F4A9AF53CF773DD102D got=841C385F9CBEAD38BAE09EAE7AC72A4AFC51F408FCF0178C1BAD477B8F0C8C40
Oct 07 22:25:32 k8s-master.provider-2.prod.ewr1 akash[457169]: E[2021-10-07|22:25:32.755] invalid manifest                             module=manifest-manager deployment=akash1apchhdvxn7u7tpnfv7c6pnhcdc7kjhcw5sz0zm/5 err="manifest version validation failed"
Oct 07 22:25:32 k8s-master.provider-2.prod.ewr1 akash[457169]: D[2021-10-07|22:25:32.755] requests valid                               module=manifest-manager deployment=akash1apchhdvxn7u7tpnfv7c6pnhcdc7kjhcw5sz0zm/5 num-requests=0
Oct 07 22:25:32 k8s-master.provider-2.prod.ewr1 akash[457169]: E[2021-10-07|22:25:32.755] manifest submit failed                       err="manifest version validation failed"
Oct 07 22:25:32 k8s-master.provider-2.prod.ewr1 akash[457169]: D[2021-10-07|22:25:32.755] emit received events skipped                 module=manifest-manager deployment=akash1apchhdvxn7u7tpnfv7c6pnhcdc7kjhcw5sz0zm/5 data="{Deployment:{DeploymentID:akash1apchhdvxn7u7tpnfv7c6pnhcdc7kjhcw5sz0zm/5 State:active Version:[56 10 22 147 190 114 148 58 174 93 70 180 17 247 10 37 226 166 217 240 24 179 47 74 154 245 60 247 115 221 16 45] CreatedAt:2968154} Groups:[{GroupID:akash1apchhdvxn7u7tpnfv7c6pnhcdc7kjhcw5sz0zm/5/1 State:open GroupSpec:{Name:main Requirements:{SignedBy:{AllOf:[] AnyOf:[akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63]} Attributes:[{Key:host Value:akash}]} Resources:[{Resources:{CPU:units:<val:\"1000\" >  Memory:quantity:<val:\"1073741824\" >  Storage:quantity:<val:\"1073741824\" >  Endpoints:[{Kind:SHARED_HTTP}]} Count:1 Price:1000uakt}]} CreatedAt:2968154}] EscrowAccount:{ID:{Scope:deployment XID:akash1apchhdvxn7u7tpnfv7c6pnhcdc7kjhcw5sz0zm/5} Owner:akash1apchhdvxn7u7tpnfv7c6pnhcdc7kjhcw5sz0zm State:open Balance:5000000uakt Transferred:0uakt SettledAt:2968162}}" manifests=0
```

[^1]: I triggered this by using an old client, that might be contributing to the problem

### PR DESCRIPTION
**Pull request by troian**
fixes #1405 

Signed-off-by: Artur Troian <troian.ap@gmail.com>

### CODE REVIEW

File: provider/cmd/manifest.go [hunk 1]
```diff
@@ -101,10 +103,12 @@ func doSendManifest(cmd *cobra.Command, sdlpath string) error {
 		res := result{
 			Provider: prov,
 			Status:   "PASS",
-			Error:    err,
 		}
-
 		if err != nil {
+			res.Error = err.Error()
+			if e, valid := err.(gwrest.ClientResponseError); valid {
```
Comment (hydrogen18) [inline provider/cmd/manifest.go:109]: Isn't this a use case for `errors.As` ?

Comment (troian) [reply provider/cmd/manifest.go:109]: `errors.As` returns bool only, still need to make type assertion to get Message from it

**Review by hydrogen18 — APPROVED** [review]
